[project]
name = "inf8415-lab1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.14.3",
    "boto3>=1.43.100",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "scipy>=1.18.1",
    "uvicorn[standard]>=0.53.0",
]
